idf_component_register(SRCS "main.c"
                            "demo_display.c"
                            "demo_button.c"
                            "demo_audio.c"
                            "demo_battery.c"
                            "app_lele_guide.c"
                            "demo_tetris.c"
                            "demo_catch.c"
                            "demo_answer.c"
                            "fonts/lv_font_cn14.c"
                            "lele_ota.c"
                            "ui_pixel.c"
                            "ui_pixel_math.c"
                       INCLUDE_DIRS "."
                       REQUIRES bsp lvgl json esp_wifi nvs_flash esp_http_client esp_https_ota app_update esp_netif esp_event)
